[[session]]
  root = "$HOME/.dotfiles"
  name = "dotfiles"
  [[session.window]]
    name = "$1"
    command = "nvim ."

[[session]]
  root = "$HOME/src/(*)"
  name = "src/$1"
  [[session.window]]
    name = "$1"
    command = "nvim ."

[[session]]
  root = "$HOME/tmp/(*)"
  name = "tmp/$1"
  [[session.window]]
    name = "$1"
    command = "nvim ."

[logger]
level = "trace"
